#!/usr/bin/env node
/**
 * Build the icon sprite from the supplied artwork, and refuse to ship a glyph
 * the product asks for but nobody drew.
 *
 * The set has been broken twice by hand-maintained copies drifting apart. Once
 * when the component's names were regenerated and the sprite was not, so 53 of
 * 107 names resolved to no symbol and rendered as nothing across the app. Then
 * again, smaller and quieter: three onboarding industry cards asked for
 * bg-broadcast, bg-shop and bg-people, which were never drawn, so Telco,
 * Fashion & Apparel and Agency showed a label with an empty space above it.
 *
 * Nothing here redraws anything. brand/icons/currentcolor is the artwork;
 * brand/icons/ink, brand/icons.svg and icon-sprite.tsx are derived from it.
 *
 *   node scripts/icons-build.mjs          build, then check
 *   node scripts/icons-build.mjs --check  check only, writes nothing
 */
import fs from 'node:fs'
import path from 'node:path'

const root = path.resolve(import.meta.dirname, '..')
const SRC = path.join(root, 'brand/icons/currentcolor')
const INK = path.join(root, 'brand/icons/ink')
const SPRITE = path.join(root, 'brand/icons.svg')
const TSX = path.join(root, 'src/components/brand/icon-sprite.tsx')
const check = process.argv.includes('--check')

const names = fs.readdirSync(SRC).filter(f => f.endsWith('.svg')).map(f => f.replace(/\.svg$/, '')).sort()
const bodyOf = n => fs.readFileSync(path.join(SRC, `${n}.svg`), 'utf8')
  .replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim()

const problems = []

/* 1. Every drawn file is a 24 grid glyph, and every glyph is drawn. */
for (const n of names) {
  const raw = fs.readFileSync(path.join(SRC, `${n}.svg`), 'utf8')
  if (!raw.includes('viewBox="0 0 24 24"')) problems.push(`${n}: not on the 24 grid`)
  if (!bodyOf(n)) problems.push(`${n}: empty`)
}

/* 2. Every id the product asks for exists. This is the check that matters:
      a <use href="#bg-x"> with no symbol behind it renders nothing at all,
      silently, and looks like a spacing bug rather than a missing icon. */
const asked = new Map()
const walk = dir => {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name)
    if (e.isDirectory()) { walk(p); continue }
    if (!/\.(ts|tsx)$/.test(e.name)) continue
    const src = fs.readFileSync(p, 'utf8')
    // Only the two shapes that reach the sprite: a BrandIconName in the union
    // or a name/icon field. Tailwind's bg-* classes never match these.
    for (const m of src.matchAll(/\b(?:name|icon)\s*[:=]\s*['"](bg-[a-z0-9-]+)['"]/g)) {
      if (!asked.has(m[1])) asked.set(m[1], `${path.relative(root, p)}`)
    }
    for (const m of src.matchAll(/\|\s*'(bg-[a-z0-9-]+)'/g)) {
      if (!asked.has(m[1])) asked.set(m[1], `${path.relative(root, p)}`)
    }
  }
}
walk(path.join(root, 'src'))
for (const [id, where] of asked) {
  if (!names.includes(id)) problems.push(`${id}: asked for in ${where}, never drawn`)
}

if (!check) {
  /* 3. The ink copies, for design tools. */
  for (const n of names) {
    const out = fs.readFileSync(path.join(SRC, `${n}.svg`), 'utf8')
      .replaceAll('stroke="currentColor"', 'stroke="#16120E"')
      .replaceAll('fill="currentColor"', 'fill="#16120E"')
    fs.writeFileSync(path.join(INK, `${n}.svg`), out)
  }

  /* 4. The sprite, and the React module that inlines it. */
  const symbols = names.map(n => `<symbol id="${n}" viewBox="0 0 24 24">${bodyOf(n)}</symbol>`)
  const banner = `BrandGauge icon set — ${names.length} glyphs.
     24 grid, 20px live area, stroke 1.75, butt caps, miter joins. Filled
     sub-paths carry their own fill and no stroke. Built from the supplied
     individual files in brand/icons/currentcolor; that is the artwork, and
     nothing here is redrawn. An icon names the thing, never the abstraction.

     Generated by scripts/icons-build.mjs. Do not edit by hand.`
  fs.writeFileSync(SPRITE,
    `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n<!-- ${banner} -->\n${symbols.join('\n')}\n</svg>\n`)

  fs.writeFileSync(TSX,
`// Generated by scripts/icons-build.mjs from brand/icons/currentcolor/*.svg —
// the supplied artwork, verbatim. Do not edit by hand; run the script.
//
// ${names.length} glyphs. Grid 24, live area 20, stroke 1.75, butt caps, miter joins.
// The stroke attributes live on the host <svg> in icon.tsx, so the symbols
// carry only the geometry and their own fills.

export function IconSprite() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" style={{ display: 'none' }} aria-hidden focusable="false">
${symbols.map(s => '      ' + s).join('\n')}
    </svg>
  )
}
`)
}

if (problems.length) {
  console.error(`icons: ${problems.length} problem${problems.length > 1 ? 's' : ''}`)
  for (const p of problems) console.error('  ' + p)
  process.exit(1)
}
console.log(`icons: ${names.length} glyphs, ${asked.size} ids referenced, all drawn${check ? '' : ' — sprite written'}`)
